Add creation of a per-segment trajectory dataset to HDF5 framework
westpa/westpa pull request #274
Opened 2022-10-13 18:48 UTC by jdrusso

**Issue Number.** N/A

**Describe the changes made.** 
The HDF5 framework stores all segment trajectories as a single concatenated trajectory. This PR adds an additional dataset, which represents the trajectories separated by segment, and ordered by segment ID.

This is achieved using a virtual dataset, so there is no redundant storage of data.

**Goals and Outstanding Issues.** A clear and concise list of goals (to be) accomplished.  
- [x] Provide easy access to per-segment trajectory data through the HDF5 framework

**Major files changed.**  
- [x] `core/data_manager.py`

**Status.**
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] I have read the CONTRIBUTING document.
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

**Additional context.** Add any other context or screenshots about the pull request here.

2022-10-17 16:23 UTC, SHZ66 requested changes

2022-10-17 16:23 UTC, SHZ66 commented on src/westpa/core/propagators/executable.py
> +        state_ref_is_h5 = 'hdf:' in struct_ref
A lot of code added here seems to fit better if they were moved to the data manager. The propagators themselves typically don't interact with the files directly, instead, they pass information to the data manager through the segment object. Please take a look at `prepare_iteration` and `update_segments` and I _think_ there's a way to move this code there.

2022-10-17 16:23 UTC, SHZ66 commented on src/westpa/core/propagators/executable.py
> +                iter_group = f'iterations/iter_{iteration:08d}'
This is not a safe assumption. Please refer to `WESTDataManager.get_iter_group` to see how to obtain the iteration group safely. Better yet, if this code is part of the data manager instead of the propagator, you could use the data manager's functions & properties to access the data more easily.

2022-10-17 16:23 UTC, SHZ66 commented on src/westpa/core/propagators/executable.py
> +            bstates = self.rc.get_data_manager().get_basis_states(n_iter=1)
It seems to me that instead of accessing the data manager here from RC, we could just move/adapt this section of code to the data manager (`prepare_iteration`).

2022-10-17 17:30 UTC, jdrusso commented on src/westpa/core/propagators/executable.py
> +        state_ref_is_h5 = 'hdf:' in struct_ref
In this section, the basis state has an HDF5 file along with segment and walker specified, *from a separate simulation*. This is not the HDF5 file generated by the current WE simulation, so the data manager has no access to this information

2022-10-26 21:13 UTC, jdrusso commented
I think rather than interacting with the H5 file directly, I can just create a *new* data manager, and then use that to interact with the H5 file

2022-10-26 21:16 UTC, jdrusso commented on src/westpa/core/data_manager.py
> +            steps_per_seg = westpa.rc.config.get(['west', 'system', 'system_options', 'pcoord_len']) - 1
This is not a good way to get this, but how can we get it without explicitly reading trajectories?

2022-10-26 21:17 UTC, jdrusso commented on src/westpa/core/data_manager.py
> +            n_dims = 3
Similarly to the above, how can we get this without explicitly reading trajectories?

2023-08-15 19:15 UTC, closed without merging